revised content of markdown files
Open-Systems-Pharmacology/Pediatric_Qualification_Package_P-gp_Ontogeny pull request #1
Opened 2023-02-16 08:25 UTC by Incei

2023-02-16 08:27 UTC, Incei commented
I somehow cannot add AndreDlm as a reviewer... ( @AndreDlm)

2023-03-17 16:34 UTC, Yuri05 commented on Input/Content/Translation.md
> +Eq. 1: $$ {\Huge  GMFE = 10^{\frac{\sum(|log(\frac{Pred}{Obs})|)}{n}} }  $$
replace $$ with $ (and no blanks after the opening $ and before the closing $):
`Eq. 1: ${\Huge  GMFE = 10^{\frac{\sum(|log(\frac{Pred}{Obs})|)}{n}} }$`
Eq. 1: ${\Huge  GMFE = 10^{\frac{\sum(|log(\frac{Pred}{Obs})|)}{n}} }$

2023-03-17 16:35 UTC, Yuri05 commented
@Incei comment out all inactivatetask lines in Workflow.R
Current workflow would fail on a new machine 
https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_P-gp_Ontogeny/blob/f08fcac54ab10fd91c650436c9fb65f62394c8a3/Workflow.R#L144-L151

2023-03-17 16:36 UTC, Yuri05 requested changes
s. comments

2023-04-04 09:19 UTC, merged